#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        2
bspc config window_gap          12

#bspc config top_padding         23

bspc config focus_follows_pointer true

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true

bspc rule -a mpv state=fullscreen
bspc rule -a 'URxvt:scratchpad' state=floating sticky=on
bspc rule -a 'Alacritty:ncmpcpp' state=floating

#picom -CGB
